### ISSUE TITLE
Custom block model parts are unlit

### ISSUE THREAD

**Issue by spiralhalo** [vram-guild/frex#3]
Same issue as https://github.com/vram-guild/canvas/issues/333 but since it seems that the light calculation have moved to Frex this might be appropriate to be posted here.

To test it I'm using FRAPI + Frex without Canvas showing "Frex compatibility wrapper" and comparing it with Indigo.

Comparison using Patrix's texture pack (basic and models packs enabled) https://www.patreon.com/posts/free-1-17-32x-54407639

![image](https://user-images.githubusercontent.com/8444172/141217836-6c79bf79-a38e-43bc-8309-9aa10fce3828.png)

Comparison using Motschen's Better Grass https://www.curseforge.com/minecraft/texture-packs/motschens-better-grass

![image](https://user-images.githubusercontent.com/8444172/141217908-cb28a77e-d03c-4838-9451-5eb184806831.png)

Relevant mods:
```
	- fabric 0.41.0+1.17
	- fermion 2.11.256
	- fermion-orientation 1.2.256
	- fermion-varia 2.6.256
	- frex 6.0.145
	- io_vram_bitkit 1.0.1
	- io_vram_bitraster 1.5.50
	- io_vram_special-circumstances 1.10.7
	- json-model-extensions 1.22.218
```

**Comment by spiralhalo** [comment]
Interestingly, the parts near a block's edge seem to be lit correctly when there is no **solid** neighbor.

![image](https://user-images.githubusercontent.com/8444172/141219087-a65e4048-33fc-4628-82da-22a83a6e4fb1.png)

**Comment by grondag** [comment]
Haven’t looked at the models but this is almost certainly happening because these models extend outside of a unit cube. Terrain lighting is absolutely not designed for that - it only sort of works in vanilla because the lighting there is crap. 

These models are sort of inherently broken in my opinion - I don’t like any model that breaks the Minecraft contract of “the world is divided into unit meters” - but leaving this open and will try to find at least  some half-assed way for them to be lit.
